[platformio]
default_envs = esp32c3

[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
lib_deps = 
	bodmer/TFT_eSPI@^2.5.43
	bblanchon/ArduinoJson@^7.0.4

build_flags = 
	-D USER_SETUP_LOADED=1
	-D ILI9341_DRIVER=1
	-D TFT_WIDTH=240
	-D TFT_HEIGHT=320
	-D TFT_MISO=2
	-D TFT_MOSI=3
	-D TFT_SCLK=4
	-D TFT_CS=7
	-D TFT_DC=6
	-D TFT_RST=5
	-D TFT_BL=8
	-D LOAD_GLCD=1
	-D LOAD_FONT2=1
	-D LOAD_FONT4=1
	-D LOAD_GFXFF=1
	-D SMOOTH_FONT=1

[env:esp8266]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
lib_deps = 
	bodmer/TFT_eSPI@^2.5.43
	bblanchon/ArduinoJson@^7.0.4

build_flags = 
	-D USER_SETUP_LOADED=1
	-D ILI9341_DRIVER=1
	-D TFT_WIDTH=240
	-D TFT_HEIGHT=320
	-D TFT_CS=PIN_D8
	-D TFT_DC=PIN_D3
	-D TFT_RST=PIN_D4
	-D LOAD_GLCD=1
	-D LOAD_FONT2=1
	-D LOAD_FONT4=1
	-D SMOOTH_FONT=1
